services:
  snaphold:
    build:
      context: .
      tags:
        - snaphold:latest
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://snaphold:password@db:5432/snaphold?schema=public&sslmode=prefer"

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: snaphold
      POSTGRES_DB: snaphold
